/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FullscreenLoading: typeof import('./src/components/layout/fullscreen-loading.vue')['default']
    HeaderNav: typeof import('./src/components/layout/header-nav.vue')['default']
    Navbar: typeof import('./src/components/layout/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TContent: typeof import('tdesign-vue-next')['Content']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TStepItem: typeof import('tdesign-vue-next')['StepItem']
    TSteps: typeof import('tdesign-vue-next')['Steps']
    TSwiper: typeof import('tdesign-vue-next')['Swiper']
    TSwiperItem: typeof import('tdesign-vue-next')['SwiperItem']
    TTag: typeof import('tdesign-vue-next')['Tag']
    UserLogin: typeof import('./src/components/user/user-login.vue')['default']
    UserLoginDialog: typeof import('./src/components/user/user-login-dialog.vue')['default']
    UserMeta: typeof import('./src/components/user/user-meta.vue')['default']
  }
}
